### ISSUE TITLE
Can I run the Nginx SSL playbook on top of the non-SSL Nginx one?

### ISSUE THREAD

**Issue by bitoiu** [versioneye/ops_contrib#12]
Hi @reiz,

I've configured Nginx successfully without SSL, as I'm generating the certs still. 

When I have them can I just do run `setup_locale_nginx_ssl.yml` or do I need to reset the configuration first? If so, how would I go about doing this. I'm afraid by running the `ssl` command the configurations can conflict, or leave debris behind :blush: 

Cheers, @bitoiu.

**Comment by reiz** [comment]
Hi @bitoiu, 

That is good question :-) I will setup a new machine today for my GitHub Enterprise setup and test it out. Later this day I let you know how it went. 

Cheers, 
Rob

**Comment by reiz** [comment]
Hi @bitoiu, 

I just setup a new instance on AWS. First with the regular Nginx config, without SSL and then with a self signed SSL certificate. That worked perfectly. I completely updated the SSL section for configuration and documentation. Please take a look [here](https://github.com/versioneye/ops_contrib/tree/master/nginx/ansible) and let me know if that works for you. 

Cheers, 
Rob

By the way, I added today a [Vagrantfile](https://github.com/versioneye/ops_contrib#vagrant). Maybe not so important for your setup, but it's nice to play with it on localhost ;-)

**Comment by bitoiu** [comment]
Thank you very much for testing this scenario @reiz :octocat::heart:
