### ISSUE TITLE
LDAP Login - DN Syntax error

### ISSUE THREAD

**Issue by yannikinniger** [versioneye/ops_contrib#17]
I can't get LDAP to work, because of the following error `An error occured! Code: 34. Message: Invalid DN Syntax invalid DN`
This is my ldap config:
![pasted image at 2017_06_07 10_31](https://user-images.githubusercontent.com/19152076/26869447-ca08e90c-4b6c-11e7-983d-284f9b269894.png)

My suspicion is that it has something to do with the filter. Do you have any idea how I could get this to work?

**Comment by reiz** [comment]
Hi @yinniger. Are you using an LDAP server or Active Directory?

**Comment by ghost** [comment]
@reiz I use LDAP Server

**Comment by reiz** [comment]
@yinniger we tested with an open LDAP server as well. I guess it's just a configuration problem. How do you run the VersionEye software? As Vagrant image? Or via docker compose? If via docker compose then configure the docker compose file that way that the log files are persisted on the host. Then you should see more log output in `enterprise_tasks.log`.
