### ISSUE TITLE
github non enterprise connection

### ISSUE THREAD

**Issue by ghost** [versioneye/ops_contrib#22]
Hi,
is it somehow possible to connection non enterprise github repositories to versioneye business? At the moment when I try to connect github to versioneye the url in the github settings is called and I could not figure out the URL for the standard github.

**Comment by reiz** [comment]
Hi @yannikinniger. If I understand you correctly you want to connect GitHub.com to your own instance of VersionEye. Right?

**Comment by reiz** [comment]
That's totally possible. It works exactly the same as with an GitHub Enterprise instance. You need to create an App in your GitHub account and use the OAuth credentials from that App. The authorization call back URL in the GitHub app has to point to your instance. For example: `https://versioneye.MyCompany.com/auth/github/callback`.

**Comment by ghost** [comment]
Thanks that worked!
