### ISSUE TITLE
About connection other host docker server

### ISSUE THREAD

**Issue by HsuNick** [versioneye/ops_contrib#23]
I have two server, one server install AP, another one server install DB.

AP install : rails_app, rails_api, tasks, crawlr, crawlj, crawlj_worker
DB install: mongodb, elasticsearch, rabbitmq, memcached

```
  external_links:
   - rabbitmq:rm
   - memcached:mc
   - elasticsearch:es
   - mongodb:db
```

I should how doing, let ap server on the container through ip & port connection db server on the container ?

sorry my english is not good.

**Comment by PhilippHeuer** [comment]
Had the same issue when i wanted to use VersionEye in Docker Swarm.

You can set custom servers using environment variables for each APP container:
```
DB_PORT_27017_TCP_ADDR: versioneye_mongodb
DB_PORT_27017_TCP_PORT: 27017
ES_PORT_9200_TCP_ADDR: versioneye_elasticsearch
ES_PORT_9200_TCP_PORT: 9200
RM_PORT_5672_TCP_ADDR: versioneye_rabbitmq
RM_PORT_5672_TCP_PORT: 5672
MC_PORT_11211_TCP_ADDR: versioneye_memcached
MC_PORT_11211_TCP_PORT: 11211
```

**Comment by HsuNick** [comment]
Thank you for helping me, It's working.
