### ISSUE TITLE
Failed to login as admin/admin

### ISSUE THREAD

**Issue by kyuff** [versioneye/ops_contrib#4]
I have run the following command and seen the application on the host.

$ docker-compose -f versioneye-base.yml up -d
$ ./versioneye-update

After entering the API key succesfully I get the login screen that tells me to login with admin/admin.
This fails with the following error: Invalid email/password combination.

Am I missing a step?

**Comment by reiz** [comment]
No, you don't miss a step. You found a bug 👍  Up to know I was setting up the instances for VersionEye Enterprise with an Ansible playbook which also did some initialization of the database. That step is missing in the Docker Compose setup. I have to think about it how to bring it tin.

**Comment by reiz** [comment]
@kyuff You can init the database with this command: 

```
docker exec -it tasks /app/init_enterprise.sh
```

That assumes that ALL VersionEye Docker Container are up and running successfully.

**Comment by reiz** [comment]
I just added a note to the README about initializing the database.
