### ISSUE TITLE
versioneye/crawlr cannot 

### ISSUE THREAD

**Issue by kyuff** [versioneye/ops_contrib#5]
After checking out this repository and starting the base services I run
$ ./versioneye-update

This gives alot of output that ends with this:

Digest: sha256:d3b236e105a11ac84c6aa0c1b136b15e76fa2f22200bc96e01b6fd6012db9afa
Status: Image is up to date for reiz/rabbitmq:3.4.2
2.3.17: Pulling from versioneye/crawlj
Digest: sha256:48908f2621a33900c6352bf1fd75091ddbf21b3ca89f8c3c153c887f133d217d
Status: Image is up to date for versioneye/crawlj:2.3.17
2.3.22: Pulling from versioneye/crawlj_worker
Digest: sha256:6a85465899882cecd1d3855e50655e6e8fdd4b4993a8b7d3437ff1579e56fc80
Status: Image is up to date for versioneye/crawlj_worker:2.3.22
Pulling repository docker.io/versioneye/crawlr
**Error: image versioneye/crawlr not found**
2.12.16: Pulling from versioneye/rails_api
Digest: sha256:546a202cf2f8b886509839f3304c2038b9e44b9ab5f027f73d5bfcba90db7258
Status: Image is up to date for versioneye/rails_api:2.12.16
4.14.1: Pulling from versioneye/rails_app
Digest: sha256:86f07fbf7aa2e3ccb54789d11103ea4ca4c470dfc744a3da3ef8fc9e25524603
Status: Image is up to date for versioneye/rails_app:4.14.1
2.3.39: Pulling from versioneye/tasks
Digest: sha256:728a4230a476e7b1a473a0d3c3b901ad1bd9259865bf5aae3bdbfda6c0ee4032
Status: Image is up to date for versioneye/tasks:2.3.39

Looking at https://www.versioneye.com/docker/remote_images.json it seems it references a docker image that cannot be found on Docker Hub.

``
{ ...
versioneye/crawlr:1.14.4: {
container_start_opts: {
Links: [
"mongodb:db",
"elasticsearch:es",
"memcached:mc",
"rabbitmq:rm"
],
Binds: [
"/mnt/cocoapods:/mnt/cocoapods",
"/mnt/logs:/app/log"
],
RestartPolicy: {
Name: "always"
}
},
auth: true,
comments: "Introduce Supervisord"
}
...
}

**Comment by reiz** [comment]
Well. That's not a bug. the `versioneye/crawlr` repo is not yet open source, but that doesn't effect the whole system. VersionEye can totally run without that Docker container.

**Comment by tomzx** [comment]
@reiz Is [`versioneye/crawl_r`](https://github.com/versioneye/crawl_r) ready to be part of `docker-compose.yml` nowadays?

**Comment by reiz** [comment]
@tomzx Yes. It's open source now and available on Docker Hub.

**Comment by tomzx** [comment]
@reiz Should it be added to https://github.com/versioneye/ops_contrib? As of https://github.com/versioneye/ops_contrib/commit/66046c51328eebc90f4f090a59d26062af2a36dd, `docker-compose.yml` makes no use of [`versioneye/crawl_r`](https://github.com/versioneye/crawl_r), hence my question.

**Comment by reiz** [comment]
@tomzx Good point! I just added it with this [commit](https://github.com/versioneye/ops_contrib/commit/c5c7d3d6301e642e981074dde3305e500b093f4c).
